FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["MyTestSalesApi.csproj", "./"]
RUN dotnet restore "MyTestSalesApi.csproj"
COPY . .
RUN dotnet publish "MyTestSalesApi.csproj" -c Release -o /app/publish


FROM mcr.microsoft.com/dotnet/sdk:8.0
WORKDIR /src
COPY --from=build /src . 
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"
ENTRYPOINT ["dotnet", "ef", "database", "update", "--project", "MyTestSalesApi.csproj"]
